import { ShoppCardProps } from '../../types/types';

export const shoppingCardsDetails: ShoppCardProps[] = [
  {
    id: 1,
    img: '/book1.png',
    name: 'Jeff Gothelf Learn UX',
    currentPrice: 100.0,
    lastPrice: 150.0,
    rating: 4.5,
    discount: '30%',
  },
  {
    id: 2,
    img: '/book2.png',
    name: 'Don Norman The Design of Everyday Things',
    currentPrice: 120.0,
    lastPrice: 180.0,
    rating: 4.8,
    discount: '20%',
  },
  {
    id: 3,
    img: '/book3.png',
    name: 'Steve Krug Don’t Make Me Think',
    currentPrice: 90.0,
    lastPrice: 140.0,
    rating: 4.7,
    discount: '35%',
  },
  {
    id: 4,
    img: '/book4.png',
    name: 'Jake Knapp Sprint',
    currentPrice: 110.0,
    lastPrice: 160.0,
    rating: 4.3,
    discount: 'None',
  },
  {
    id: 5,
    img: '/book5.png',
    name: 'Alan Cooper About Face',
    currentPrice: 130.0,
    lastPrice: 190.0,
    rating: 4.6,
    discount: '30%',
  },
  {
    id: 6,
    img: '/book6.png',
    name: 'Erik Spiekermann Stop Stealing Sheep',
    currentPrice: 80.0,
    lastPrice: 130.0,
    rating: 4.2,
    discount: '40%',
  },
  {
    id: 7,
    img: '/book7.png',
    name: 'Susan Weinschenk 100 Things Every Designer Needs to Know',
    currentPrice: 95.0,
    lastPrice: 145.0,
    rating: 4.4,
    discount: 'None',
  },
  {
    id: 8,
    img: '/book8.png',
    name: 'Ethan Marcotte Responsive Web Design',
    currentPrice: 105.0,
    lastPrice: 155.0,
    rating: 4.6,
    discount: '30%',
  },
  {
    id: 9,
    img: '/book1.png',
    name: 'Scott Hurff Designing Products People Love',
    currentPrice: 125.0,
    lastPrice: 175.0,
    rating: 4.5,
    discount: '25%',
  },
  {
    id: 10,
    img: '/book2.png',
    name: 'Jon Yablonski Laws of UX',
    currentPrice: 115.0,
    lastPrice: 165.0,
    rating: 4.7,
    discount: 'None',
  },
  {
    id: 11,
    img: '/book3.png',
    name: 'Chris Nodder Evil by Design',
    currentPrice: 85.0,
    lastPrice: 135.0,
    rating: 4.1,
    discount: '45%',
  },
  {
    id: 12,
    img: '/book4.png',
    name: 'Dan Saffer Microinteractions',
    currentPrice: 100.0,
    lastPrice: 150.0,
    rating: 4.5,
    discount: '30%',
  },
  {
    id: 13,
    img: '/book5.png',
    name: 'Victor Papanek Design for the Real World',
    currentPrice: 140.0,
    lastPrice: 200.0,
    rating: 4.8,
    discount: 'None',
  },
  {
    id: 14,
    img: '/book6.png',
    name: 'Robin Williams The Non-Designer’s Design Book',
    currentPrice: 75.0,
    lastPrice: 125.0,
    rating: 4.0,
    discount: '50%',
  },
  {
    id: 15,
    img: '/book7.png',
    name: 'Kim Goodwin Designing for the Digital Age',
    currentPrice: 135.0,
    lastPrice: 185.0,
    rating: 4.9,
    discount: '20%',
  },
  {
    id: 16,
    img: '/book8.png',
    name: 'Luke Wroblewski Mobile First',
    currentPrice: 95.0,
    lastPrice: 145.0,
    rating: 4.3,
    discount: 'None',
  },
  {
    id: 17,
    img: '/book1.png',
    name: 'Edward R. Tufte The Visual Display of Quantitative Information',
    currentPrice: 110.0,
    lastPrice: 160.0,
    rating: 4.6,
    discount: '30%',
  },
  {
    id: 18,
    img: '/book2.png',
    name: 'Ben Shneiderman Designing the User Interface',
    currentPrice: 125.0,
    lastPrice: 175.0,
    rating: 4.4,
    discount: '25%',
  },
  {
    id: 19,
    img: '/book3.png',
    name: 'Brenda Laurel Computers as Theatre',
    currentPrice: 105.0,
    lastPrice: 155.0,
    rating: 4.2,
    discount: '40%',
  },
  {
    id: 20,
    img: '/book4.png',
    name: 'Bill Buxton Sketching User Experiences',
    currentPrice: 130.0,
    lastPrice: 180.0,
    rating: 4.5,
    discount: '30%',
  },
  {
    id: 21,
    img: '/book5.png',
    name: 'Donald A. Norman Emotional Design',
    currentPrice: 115.0,
    lastPrice: 165.0,
    rating: 4.7,
    discount: 'None',
  },
  {
    id: 22,
    img: '/book6.png',
    name: 'Alan Dix Human-Computer Interaction',
    currentPrice: 135.0,
    lastPrice: 185.0,
    rating: 4.8,
    discount: '25%',
  },
  {
    id: 23,
    img: '/book7.png',
    name: 'Jan Tschichold The New Typography',
    currentPrice: 95.0,
    lastPrice: 145.0,
    rating: 4.3,
    discount: '35%',
  },
  {
    id: 24,
    img: '/book8.png',
    name: 'Ellen Lupton Thinking with Type',
    currentPrice: 100.0,
    lastPrice: 150.0,
    rating: 4.5,
    discount: '30%',
  },
];
